---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::agat=1.6.1
  - conda-forge::python=3.
  - conda-forge::pyyaml=6.0
